<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPsIdzxa\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPsIdzxa/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerPsIdzxa.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerPsIdzxa\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerPsIdzxa\appAppKernelProdContainer([
    'container.build_hash' => 'PsIdzxa',
    'container.build_id' => '6027381a',
    'container.build_time' => 1742242026,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPsIdzxa');
